//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UriJudge.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UriJudge.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N O V E L  
        ///  
        ///Defining the genre
        ///==================
        /// 
        ///A novel is a long, fictional narrative which describes intimate human experiences. The novel in the modern era usually makes use of a literary prose style, and the development of the prose novel at
        ///this time was encouraged by innovations in printing, and the introduction of cheap paper, in the 15th century.
        ///
        ///The present English (and Spanish) word for a long work of prose fiction derives from the Italian novella for &quot;new&quot;, &quot;news&quot;, or &quot;short story [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AndyDictionaryText1 {
            get {
                return ResourceManager.GetString("AndyDictionaryText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex(*$a#.mpl.e:
        ///
        ///Adventures in Disneyland
        ///
        ///Two blondes were going to Disneyland when they came to a fork in the road. The sign read: &quot;Disneyland LEFT.&quot; 
        ///
        ///So they went home..
        /// </summary>
        internal static string AndyDictionaryText2 {
            get {
                return ResourceManager.GetString("AndyDictionaryText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ability
        ///about
        ///abridgements
        ///abridgments
        ///abstract
        ///academic
        ///acceptance
        ///accepted
        ///accessible
        ///accounts
        ///accused
        ///achievements
        ///acknowledged
        ///action
        ///actions
        ///ad
        ///ada
        ///adaptation
        ///add
        ///added
        ///addition
        ///addressed
        ///addresses
        ///adopted
        ///advance
        ///advantage
        ///advantages
        ///adventure
        ///adventures
        ///advertised
        ///aeneid
        ///aesthetes
        ///affairs
        ///affordable
        ///after
        ///again
        ///against
        ///age
        ///ages
        ///aim
        ///al
        ///alain
        ///albert
        ///aldous
        ///alem
        ///alessandro
        ///alexander
        ///alexanderplatz
        ///alfred
        ///algernon
        ///all
        ///allegations
        ///allegedly
        ///allow
        ///al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AndyDictionaryWords1 {
            get {
                return ResourceManager.GetString("AndyDictionaryWords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///adventures
        ///blondes
        ///came
        ///disneyland
        ///e
        ///ex
        ///fork
        ///going
        ///home
        ///in
        ///left
        ///mpl
        ///read
        ///road
        ///sign
        ///so
        ///the
        ///they
        ///to
        ///two
        ///went
        ///were
        ///when.
        /// </summary>
        internal static string AndyDictionaryWords2 {
            get {
                return ResourceManager.GetString("AndyDictionaryWords2", resourceCulture);
            }
        }
    }
}
